### ISSUE TITLE
Add Android And IOS support.

### ISSUE THREAD

**Issue by adderly** [KDE/snorenotify#12]
It would be nice to have support for them.

**Comment by TheOneRing** [comment]
Which notification apps are popular on those platforms?

**Comment by TheOneRing** [comment]
https://play.google.com/store/apps/details?id=com.usk.app.notifymyandroid ?

**Comment by adderly** [comment]
Yeah, something like that. At the basic, toasts and reminders are the most used. Don't really know if it fits to the reach of this project.

**Comment by TheOneRing** [comment]
do you intend to use libsnore in an android/ios application?
Support for that is not yet planned.
But out of curiosity, for android I could use an emulator to implement the support and for ios?

**Comment by adderly** [comment]
Yes, you could. I am developing a multiplatform app with qt, and it became a handy to control notifications from one code base. I have no time to add these to Snorenotify codebase right now, i might as my app develops.

**Comment by TheOneRing** [comment]
would be great as I have no experience in android development and don't even own an android device

**Comment by TheOneRing** [comment]
Moving issue to KDE Phabricator https://phabricator.kde.org/T849
