### ISSUE TITLE
support for win phone?

### ISSUE THREAD

**Issue by Ashish-Bansal** [KDE/snorenotify#13]
Hey, It was unclear from the description that whether this framework is supported on windows phone 8.1(win rt) or not ?
Although It might seem to be obvious as if it supports win8.1 on pc then it must support windows phone too because of WinRT but I still want to confirm that!

**Regards**
**Ashish Bansal**

**Comment by TheOneRing** [comment]
Hi currently windows phone is not supported. The Windows 8 backend is calling an external executable as there are currently to many problems with the desktop version of Qt.
But I might look into windows phone support, I have one, and https://github.com/Snorenotify/Snoretoast already offers a dll so we will see.

**Comment by TheOneRing** [comment]
Moving issue to KDE Phabricator https://phabricator.kde.org/T849
