### ISSUE TITLE
Question: First notfication

### ISSUE THREAD

**Issue by saeschdivara** [KDE/snorenotify#19]
Hi

Since I have found nothing in the documentation, I wanted to ask if you could give me a small example how to display my first notfication.

By the way, I am using OS X 10.10.

Thx

**Comment by jendas1** [comment]
Try to compile this simple example. Just comment the line with delivery date (It is not supported yet). https://github.com/jendas1/Snorenotify/tree/master/examples/Simplest%20notification

**Comment by jendas1** [comment]
PS: Make sure you have installed SnoreNotify.
cd this-repo; mkdir build; cd build; cmake .. ; make install

**Comment by jendas1** [comment]
If cmake can't find Qt include Qt in CMAKE_PREFIX_PATH

**Comment by saeschdivara** [comment]
Well I have just used the code in my project but I get the following message:

../src/main.cpp:56:7: error: no member named 'setDeliveryDate' in 'Snore::Notification'
    n.setDeliveryDate(QDateTime::currentDateTime().addSecs(5));

**Comment by saeschdivara** [comment]
Sorry I have just read your first comment ;)

And thanks, the code worked for me :)
I saw my first notification

**Comment by saeschdivara** [comment]
It would be great if someone could add this example or add something to the README or add it to the documentation

**Comment by TheOneRing** [comment]
Moving issue to KDE Phabricator https://phabricator.kde.org/T848
